list:
    resource: ../../src/Controller/BoardList.php
    type: annotation

thread:
    resource: ../../src/Controller/BoardThread.php
    type: annotation

show:
    resource: ../../src/Controller/Board.php
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
